spring.application.name=QuizWebApp

spring.security.user.name=tsl
spring.security.user.password=1234

server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/Quize_DB
spring.datasource.username=postgres
spring.datasource.password=Tanmay@2000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true